### ISSUE TITLE
Excuse me, can I ask you for a data set in the paper?

### ISSUE THREAD

**Issue by xuliji** [jviquerat/twin_autoencoder#1]
#### We are deeply inspired by your paper, so we want to continue to do some work related to your paper and quote your paper. I would appreciate it if you could share your dataset.

**Comment by jviquerat** [comment]
Hi, the code that goes with the paper was just pushed. The dataset is available here : https://cloud.mines-paristech.fr/index.php/s/6ezipdmzj1uwPcW

**Comment by xuliji** [comment]
#### thank you very much
